Remove ugle config
```
set autoindent
set expandtab
```

This two config will auto convert tab into 4 spaces, WTF.
Which will cause a problem for python code:
```
TabError: inconsistent use of tabs and spaces in indentation
```